apiVersion: v1
kind: Namespace
metadata:
  name: nginx-cd-relaxmanitstime
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-cd-relaxmanitstime
data:
  index.html: |
    <html>
    <head><title>Hello DevOps</title></head>
    <body><h1>Hello!!! DevOps</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-cd-relaxmanitstime
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html-config
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-cd-relaxmanitstime
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
